Tweaks to docs that I'm finding need to be done while working on a talk for appsec.org.nz con
purpleteam-labs/purpleteam-doc pull request #1
Opened 2021-01-19 08:06 UTC by binarymist

* Added _Outcomes_ to definitions.md and alphabetically sorted records
* Small tweak to local.md

### Checklist

* [x] I have read the contributing guidelines
* [x] I have read the documentation
* [x] I have included a descriptive Pull Request title
* [x] I have included a Pull Request description of my changes
* [x] I have included tests where/when required (see contributing guidelines)
* [x] I have included documentation modifications/additions where/when required (see contributing guidelines)

2021-01-19 16:24 UTC, ricekot requested changes

2021-01-19 16:24 UTC, ricekot commented on definitions.md
>  | _Test&nbsp;Run_     | The back-end process running that the _orchestrator_ is responsible for. This is the combination of the running _orchestrator_ looking after the _Testers_, which are executing
It is suggested to break long sentences into shorter ones for better comprehension:
https://developers.google.com/tech-writing/one/short-sentences#focus_each_sentence_on_a_single_idea

```suggestion
| _Test&nbsp;Run_     | The back-end process running that the _orchestrator_ is responsible for. This is the combination of the running _orchestrator_ looking after the _Testers_. _Testers_ execute the _Job_ and interact with the _Emissaries_ for which they are responsible
```
Question: _This is the combination of the running orchestrator and...?_

I feel that the info about the _Testers_ can be moved to their definition.

2021-01-19 16:24 UTC, ricekot commented on definitions.md
> +| _Outcomes_          | Resources (generally in the form of files) that are generated by _Testers_ and transferred from the _orchestrator_ (or API in the `cloud` environment) to a file path location
Consider adding a definition for _Orchestrator_?

2021-01-19 16:24 UTC, ricekot commented on local.md
> +If running in the `cloud` environment most of this is unnecessary. You will of course still need your system under test (SUT) to be running and in a clean state before starting tests.
```suggestion
If running in the `cloud` environment most of this is unnecessary. You will still need your system under test (SUT) to be running and in a clean state before starting tests.
```
Matter of preference, feel free to leave it in.

2021-01-20 02:34 UTC, binarymist commented on definitions.md
>  | _Emissary/Emissaries_ | Containerised tools that do the _Testers_ bidding, ZapAPI, Nikto, sslyze, etc. The intention is that you will be able to add your own
Actually the plural of `Tester` is `Testers` unless it's possessive.

* For us there is no ownership involved (`Tester's` or `Tester'`)
* Plural showing possession (`Testers'`). For us there is no possession

[Source](https://grammar.yourdictionary.com/punctuation/apostrophe-rules.html)

2021-01-20 03:03 UTC, binarymist commented on definitions.md
>  | _Test&nbsp;Run_     | The back-end process running that the _orchestrator_ is responsible for. This is the combination of the running _orchestrator_ looking after the _Testers_, which are executing
Have moved the part about the Testers to their own definition

2021-01-20 03:18 UTC, binarymist commented on definitions.md
> +| _Outcomes_          | Resources (generally in the form of files) that are generated by _Testers_ and transferred from the _orchestrator_ (or API in the `cloud` environment) to a file path location
Yeah, there are a lot of things we can still add. I'm hoping they'll be picked up in #37

2021-01-20 03:42 UTC, binarymist commented on definitions.md
> +| _Outcomes_          | Resources (generally in the form of files) that are generated by _Testers_ and transferred from the _orchestrator_ (or API in the `cloud` environment) to a file path location
Have added a record for orchestrator.

2021-01-20 03:47 UTC, binarymist commented on local.md
> +If running in the `cloud` environment most of this is unnecessary. You will of course still need your system under test (SUT) to be running and in a clean state before starting tests.
I agree. I've changed this.

2021-01-20 04:05 UTC, binarymist commented
Squashed commits and force pushed. See what you think now @ricekot

2021-01-20 09:23 UTC, ricekot commented on definitions.md
>  | _Emissary/Emissaries_ | Containerised tools that do the _Testers_ bidding, ZapAPI, Nikto, sslyze, etc. The intention is that you will be able to add your own
Hmmm. I still think it should be "Testers' bidding" or "bidding of the Testers". In other cases we do put an apostrophe, for example, 
- He attended law school at his father's bidding.
- The servant grumbled but did his employer's bidding.

[Source](https://idioms.thefreedictionary.com/do+one%27s+bidding)

In any case, I don't think it matters that much, we are not writing a grammar book 😅.

2021-01-20 09:28 UTC, ricekot commented on definitions.md
> +| _Test&nbsp;Run_     | This is the back-end activity initiated by the CLI that tests the customer's _SUT_. The _orchestrator_ is responsible for coordinating this activity. The _orchestrator_ coordi
```suggestion
| _Test&nbsp;Run_     | This is the back-end activity initiated by the CLI that tests the customer's _SUT_. The _orchestrator_ is responsible for coordinating this activity and the _Testers_
```

2021-01-21 03:19 UTC, binarymist commented on definitions.md
>  | _Emissary/Emissaries_ | Containerised tools that do the _Testers_ bidding, ZapAPI, Nikto, sslyze, etc. The intention is that you will be able to add your own
> * He attended law school at his father's bidding.
> * The servant grumbled but did his employer's bidding.

Yes, that's because it's possessive.

2021-01-21 03:25 UTC, binarymist commented on definitions.md
> +| _Test&nbsp;Run_     | This is the back-end activity initiated by the CLI that tests the customer's _SUT_. The _orchestrator_ is responsible for coordinating this activity. The _orchestrator_ coordi
Good idea!

2021-01-21 03:49 UTC, merged

2021-01-21 03:49 UTC, nzquail commented
Looks good :-)

2021-01-21 03:57 UTC, binarymist commented
Squashed and merged
Thanks @ricekot & @nzquail